import * as crypto from 'crypto';

/**
 * Auth for remote access. The token doubles as the opaque session cookie value:
 * it is generated by OmniDesk, shown in the settings panel, and required on both
 * the HTTP layer (cookie) and the WebSocket upgrade.
 */
export class RemoteAuth {
  static readonly COOKIE = 'omnidesk_remote';

  private token: string;
  private readonly attempts = new Map<string, { count: number; first: number }>();
  private readonly WINDOW_MS = 60_000;
  private readonly MAX_ATTEMPTS = 10;

  constructor(token?: string) {
    this.token = token ?? RemoteAuth.generateToken();
  }

  static generateToken(): string {
    return crypto.randomBytes(24).toString('base64url');
  }

  getToken(): string {
    return this.token;
  }

  regenerate(): string {
    this.token = RemoteAuth.generateToken();
    return this.token;
  }

  verify(candidate: string): boolean {
    if (!candidate) return false;
    const a = Buffer.from(candidate);
    const b = Buffer.from(this.token);
    if (a.length !== b.length) return false;
    return crypto.timingSafeEqual(a, b);
  }

  cookieValid(cookieHeader: string | undefined): boolean {
    if (!cookieHeader) return false;
    const entry = cookieHeader
      .split(';')
      .map((s) => s.trim())
      .find((s) => s.startsWith(`${RemoteAuth.COOKIE}=`));
    if (!entry) return false;
    return this.verify(entry.slice(RemoteAuth.COOKIE.length + 1));
  }

  buildSetCookie(secure: boolean): string {
    const parts = [
      `${RemoteAuth.COOKIE}=${this.token}`,
      'HttpOnly',
      'SameSite=Strict',
      'Path=/',
    ];
    if (secure) parts.push('Secure');
    return parts.join('; ');
  }

  rateLimited(ip: string): boolean {
    const now = Date.now();
    const rec = this.attempts.get(ip);
    if (!rec || now - rec.first > this.WINDOW_MS) {
      this.attempts.set(ip, { count: 1, first: now });
      return false;
    }
    rec.count += 1;
    return rec.count > this.MAX_ATTEMPTS;
  }
}
