#!/usr/bin/env node
/**
 * Generates platform-specific app icons from the OmniDesk design.
 *
 * Outputs:
 *   resources/icon.png   (1024x1024 — Linux + source)
 *   resources/icon.ico   (Windows — multi-size)
 *   resources/icon.icns  (macOS — generated by electron-builder from PNG)
 *
 * Usage: node scripts/generate-icons.mjs
 */

import sharp from 'sharp';
import pngToIco from 'png-to-ico';
import { writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const RESOURCES = join(ROOT, 'resources');

// OmniDesk icon — "O" as an SVG path (font-independent)
// Design: Tokyo Night dark bg, rounded rect, bold monospace "C", green progress bar
function createIconSVG(size) {
  const scale = size / 512;
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 512 512">
  <defs>
    <linearGradient id="bgGrad" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#1e1f2e"/>
      <stop offset="100%" stop-color="#16171f"/>
    </linearGradient>
    <linearGradient id="barGrad" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0%" stop-color="#7aa2f7"/>
      <stop offset="50%" stop-color="#9ece6a"/>
      <stop offset="100%" stop-color="#7aa2f7"/>
    </linearGradient>
    <filter id="glow">
      <feGaussianBlur stdDeviation="3" result="blur"/>
      <feComposite in="SourceGraphic" in2="blur" operator="over"/>
    </filter>
    <filter id="textShadow">
      <feDropShadow dx="0" dy="2" stdDeviation="4" flood-color="#7aa2f7" flood-opacity="0.3"/>
    </filter>
  </defs>

  <!-- Background -->
  <rect width="512" height="512" rx="80" fill="url(#bgGrad)"/>

  <!-- Subtle border -->
  <rect width="512" height="512" rx="80" fill="none" stroke="#292e42" stroke-width="2"/>

  <!-- Terminal cursor block (subtle) -->
  <rect x="310" y="150" width="16" height="180" rx="2" fill="#c0caf5" opacity="0.15"/>

  <!-- "C" letter — bold monospace style, as SVG path -->
  <g filter="url(#textShadow)">
    <path d="
      M 310 148
      C 290 120, 260 108, 228 108
      C 155 108, 118 164, 118 240
      C 118 316, 155 372, 228 372
      C 260 372, 290 360, 310 332
      L 310 370
      C 285 394, 255 408, 220 408
      C 128 408, 76 334, 76 240
      C 76 146, 128 72, 220 72
      C 255 72, 285 86, 310 110
      Z
    " fill="#7aa2f7"/>
  </g>

  <!-- Progress bar track -->
  <rect x="76" y="430" width="360" height="6" rx="3" fill="#292e42"/>

  <!-- Progress bar fill -->
  <rect x="76" y="430" width="200" height="6" rx="3" fill="url(#barGrad)" filter="url(#glow)"/>

  <!-- Terminal dots (top-left, subtle) -->
  <circle cx="96" cy="44" r="6" fill="#f7768e" opacity="0.7"/>
  <circle cx="118" cy="44" r="6" fill="#e0af68" opacity="0.7"/>
  <circle cx="140" cy="44" r="6" fill="#9ece6a" opacity="0.7"/>
</svg>`;
}

async function main() {
  mkdirSync(RESOURCES, { recursive: true });

  console.log('Generating OmniDesk app icons...\n');

  // Generate 1024x1024 master PNG
  const svg1024 = Buffer.from(createIconSVG(1024));
  const png1024 = await sharp(svg1024).png().toBuffer();
  writeFileSync(join(RESOURCES, 'icon.png'), png1024);
  console.log('  ✓ icon.png (1024x1024)');

  // Generate smaller PNGs for .ico
  const sizes = [256, 128, 64, 48, 32, 16];
  const pngBuffers = [];

  for (const size of sizes) {
    const svg = Buffer.from(createIconSVG(size));
    const png = await sharp(svg)
      .resize(size, size, { fit: 'contain' })
      .png()
      .toBuffer();
    pngBuffers.push(png);
  }

  // Generate .ico (Windows) — multi-size
  const icoBuffer = await pngToIco(pngBuffers);
  writeFileSync(join(RESOURCES, 'icon.ico'), icoBuffer);
  console.log('  ✓ icon.ico (256, 128, 64, 48, 32, 16)');

  // Also write standard Linux icon sizes + 512x512 for electron-builder .icns conversion
  const linuxDir = join(RESOURCES, 'icons');
  mkdirSync(linuxDir, { recursive: true });

  const svg512 = Buffer.from(createIconSVG(512));
  const png512 = await sharp(svg512).png().toBuffer();
  writeFileSync(join(linuxDir, '512x512.png'), png512);
  for (let i = 0; i < sizes.length; i++) {
    writeFileSync(join(linuxDir, `${sizes[i]}x${sizes[i]}.png`), pngBuffers[i]);
  }
  writeFileSync(join(linuxDir, '1024x1024.png'), png1024);
  console.log('  ✓ icons/ (Linux sizes: 16–1024)');

  console.log('\nDone! Icons written to resources/');
  console.log('\nNote: .icns (macOS) is auto-generated by electron-builder from icon.png during packaging.');
}

main().catch(err => {
  console.error('Failed to generate icons:', err);
  process.exit(1);
});
