#!/usr/bin/env node
/**
 * Generates platform-specific app icons from the OmniDesk BrandMark.
 *
 * Outputs:
 *   resources/icon.png   (1024x1024 — Linux + source)
 *   resources/icon.ico   (Windows — multi-size)
 *
 * Usage: node scripts/generate-icons.mjs
 */

import sharp from 'sharp';
import { writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const RESOURCES = join(ROOT, 'resources');

// -- BrandMark geometry (mirrors BrandMark.tsx exactly) --
const cx = 32, cy = 32, r = 16, ext = 10;
const toRad = (deg) => (deg * Math.PI) / 180;
const hex = (deg) => ({
  x: cx + r * Math.cos(toRad(deg)),
  y: cy + r * Math.sin(toRad(deg)),
});
const extPt = (deg) => ({
  x: cx + (r + ext) * Math.cos(toRad(deg)),
  y: cy + (r + ext) * Math.sin(toRad(deg)),
});

const angles = [0, 60, 120, 180, 240, 300];
const vertices = angles.map(hex);
const hexPath = vertices
  .map((v, i) => `${i === 0 ? 'M' : 'L'}${v.x.toFixed(2)},${v.y.toFixed(2)}`)
  .join(' ') + ' Z';

const extAngles = [0, 120, 240];
const extLines = extAngles.map((deg) => {
  const s = hex(deg), e = extPt(deg);
  return `<line x1="${s.x.toFixed(2)}" y1="${s.y.toFixed(2)}" x2="${e.x.toFixed(2)}" y2="${e.y.toFixed(2)}" stroke="#00C9A7" stroke-width="2.5" stroke-linecap="round"/>`;
}).join('\n    ');

function createIconSVG() {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 64 64">
  <defs>
    <clipPath id="rounded">
      <rect width="64" height="64" rx="12" ry="12"/>
    </clipPath>
  </defs>
  <g clip-path="url(#rounded)">
    <rect width="64" height="64" fill="#0D0E14"/>
    <path d="${hexPath}" stroke="#00C9A7" stroke-width="2.5" stroke-linejoin="round" fill="none"/>
    ${extLines}
    <circle cx="${cx}" cy="${cy}" r="2.5" fill="#00C9A7"/>
  </g>
</svg>`;
}

// -- ICO file builder (PNG-encoded, no extra deps) --
function createIco(pngBuffers, sizes) {
  const numImages = pngBuffers.length;
  const headerSize = 6;
  const dirEntrySize = 16;
  let dataOffset = headerSize + dirEntrySize * numImages;

  const entries = pngBuffers.map((png, i) => {
    const s = sizes[i] >= 256 ? 0 : sizes[i];
    const entry = { width: s, height: s, offset: dataOffset, size: png.length };
    dataOffset += png.length;
    return entry;
  });

  const buf = Buffer.alloc(dataOffset);
  buf.writeUInt16LE(0, 0);          // reserved
  buf.writeUInt16LE(1, 2);          // type: ICO
  buf.writeUInt16LE(numImages, 4);  // image count

  entries.forEach((e, i) => {
    const off = headerSize + i * dirEntrySize;
    buf.writeUInt8(e.width, off);
    buf.writeUInt8(e.height, off + 1);
    buf.writeUInt8(0, off + 2);          // palette
    buf.writeUInt8(0, off + 3);          // reserved
    buf.writeUInt16LE(1, off + 4);       // color planes
    buf.writeUInt16LE(32, off + 6);      // bpp
    buf.writeUInt32LE(e.size, off + 8);  // data size
    buf.writeUInt32LE(e.offset, off + 12);
  });

  pngBuffers.forEach((png, i) => png.copy(buf, entries[i].offset));
  return buf;
}

async function main() {
  mkdirSync(RESOURCES, { recursive: true });
  console.log('Generating OmniDesk app icons...\n');

  const svgBuffer = Buffer.from(createIconSVG());

  // 1024x1024 master PNG
  const png1024 = await sharp(svgBuffer).resize(1024, 1024).png().toBuffer();
  writeFileSync(join(RESOURCES, 'icon.png'), png1024);
  console.log('  icon.png (1024x1024)');

  // Windows ICO (multi-size)
  const icoSizes = [16, 32, 48, 64, 128, 256];
  const pngBuffers = await Promise.all(
    icoSizes.map((s) => sharp(svgBuffer).resize(s, s).png().toBuffer())
  );
  writeFileSync(join(RESOURCES, 'icon.ico'), createIco(pngBuffers, icoSizes));
  console.log(`  icon.ico (${icoSizes.join(', ')}px)`);

  // Linux icon sizes
  const linuxDir = join(RESOURCES, 'icons');
  mkdirSync(linuxDir, { recursive: true });
  const allSizes = [16, 32, 48, 64, 128, 256, 512, 1024];
  for (const s of allSizes) {
    const png = s === 1024 ? png1024 : await sharp(svgBuffer).resize(s, s).png().toBuffer();
    writeFileSync(join(linuxDir, `${s}x${s}.png`), png);
  }
  console.log('  icons/ (Linux: 16-1024)');

  console.log('\nDone! .icns is auto-generated by electron-builder from icon.png.');
}

main().catch(err => {
  console.error('Failed:', err);
  process.exit(1);
});
